/**
 * GENERATED by tools/provider-catalog/build.ts — do not edit by hand.
 *   npm run catalog:providers
 *
 * Pi's provider registry, reduced to what HappyVibe can actually offer as a
 * one-key setup. Every exclusion is derived from what upstream declares (see
 * the generator header); tests/provider-catalog.test.ts re-derives this file
 * from the vendored pi-ai and fails when a pin bump changes it, so a new
 * provider arrives as a red test rather than as silent drift.
 *
 * `providerIds` is every Pi provider id one key unlocks — several brands ship
 * a regional twin behind the same variable.
 */

export interface CatalogProvider {
  /** Canonical Pi provider id — also the config key a stored key is filed under. */
  id: string;
  /** Upstream's own display name. */
  label: string;
  envVar: string;
  /** For the save-time key probe. null ⇒ probe skipped ("couldn't verify"). */
  baseUrl: string | null;
  modelCount: number;
  providerIds: readonly string[];
}

export interface CatalogOAuthProvider {
  id: string;
  label: string;
  /** Upstream's own button copy. */
  loginLabel?: string;
  isSubscription?: boolean;
}

export const PROVIDER_CATALOG: readonly CatalogProvider[] = [
  {
    "id": "ant-ling",
    "label": "Ant Ling",
    "envVar": "ANT_LING_API_KEY",
    "baseUrl": "https://api.ant-ling.com/v1",
    "modelCount": 3,
    "providerIds": [
      "ant-ling"
    ]
  },
  {
    "id": "anthropic",
    "label": "Anthropic",
    "envVar": "ANTHROPIC_API_KEY",
    "baseUrl": "https://api.anthropic.com",
    "modelCount": 14,
    "providerIds": [
      "anthropic"
    ]
  },
  {
    "id": "baseten",
    "label": "Baseten",
    "envVar": "BASETEN_API_KEY",
    "baseUrl": "https://inference.baseten.co/v1",
    "modelCount": 21,
    "providerIds": [
      "baseten"
    ]
  },
  {
    "id": "cerebras",
    "label": "Cerebras",
    "envVar": "CEREBRAS_API_KEY",
    "baseUrl": "https://api.cerebras.ai/v1",
    "modelCount": 2,
    "providerIds": [
      "cerebras"
    ]
  },
  {
    "id": "deepseek",
    "label": "DeepSeek",
    "envVar": "DEEPSEEK_API_KEY",
    "baseUrl": "https://api.deepseek.com",
    "modelCount": 2,
    "providerIds": [
      "deepseek"
    ]
  },
  {
    "id": "fireworks",
    "label": "Fireworks",
    "envVar": "FIREWORKS_API_KEY",
    "baseUrl": "https://api.fireworks.ai/inference",
    "modelCount": 33,
    "providerIds": [
      "fireworks"
    ]
  },
  {
    "id": "google",
    "label": "Google",
    "envVar": "GEMINI_API_KEY",
    "baseUrl": "https://generativelanguage.googleapis.com/v1beta",
    "modelCount": 22,
    "providerIds": [
      "google"
    ]
  },
  {
    "id": "groq",
    "label": "Groq",
    "envVar": "GROQ_API_KEY",
    "baseUrl": "https://api.groq.com/openai/v1",
    "modelCount": 7,
    "providerIds": [
      "groq"
    ]
  },
  {
    "id": "huggingface",
    "label": "Hugging Face",
    "envVar": "HF_TOKEN",
    "baseUrl": "https://router.huggingface.co/v1",
    "modelCount": 75,
    "providerIds": [
      "huggingface"
    ]
  },
  {
    "id": "kimi-coding",
    "label": "Kimi For Coding",
    "envVar": "KIMI_API_KEY",
    "baseUrl": "https://api.kimi.com/coding",
    "modelCount": 4,
    "providerIds": [
      "kimi-coding"
    ]
  },
  {
    "id": "meta",
    "label": "Meta",
    "envVar": "META_API_KEY",
    "baseUrl": "https://api.meta.ai/v1",
    "modelCount": 5,
    "providerIds": [
      "meta"
    ]
  },
  {
    "id": "minimax",
    "label": "MiniMax",
    "envVar": "MINIMAX_API_KEY",
    "baseUrl": "https://api.minimax.io/anthropic",
    "modelCount": 3,
    "providerIds": [
      "minimax"
    ]
  },
  {
    "id": "minimax-cn",
    "label": "MiniMax CN",
    "envVar": "MINIMAX_CN_API_KEY",
    "baseUrl": "https://api.minimaxi.com/anthropic",
    "modelCount": 3,
    "providerIds": [
      "minimax-cn"
    ]
  },
  {
    "id": "mistral",
    "label": "Mistral",
    "envVar": "MISTRAL_API_KEY",
    "baseUrl": "https://api.mistral.ai",
    "modelCount": 33,
    "providerIds": [
      "mistral"
    ]
  },
  {
    "id": "moonshotai",
    "label": "Moonshot AI",
    "envVar": "MOONSHOT_API_KEY",
    "baseUrl": "https://api.moonshot.ai/v1",
    "modelCount": 8,
    "providerIds": [
      "moonshotai",
      "moonshotai-cn"
    ]
  },
  {
    "id": "nvidia",
    "label": "NVIDIA",
    "envVar": "NVIDIA_API_KEY",
    "baseUrl": "https://integrate.api.nvidia.com/v1",
    "modelCount": 20,
    "providerIds": [
      "nvidia"
    ]
  },
  {
    "id": "openai",
    "label": "OpenAI",
    "envVar": "OPENAI_API_KEY",
    "baseUrl": "https://api.openai.com/v1",
    "modelCount": 39,
    "providerIds": [
      "openai"
    ]
  },
  {
    "id": "opencode",
    "label": "OpenCode Zen",
    "envVar": "OPENCODE_API_KEY",
    "baseUrl": "https://opencode.ai/zen",
    "modelCount": 97,
    "providerIds": [
      "opencode",
      "opencode-go"
    ]
  },
  {
    "id": "openrouter",
    "label": "OpenRouter",
    "envVar": "OPENROUTER_API_KEY",
    "baseUrl": "https://openrouter.ai/api/v1",
    "modelCount": 380,
    "providerIds": [
      "openrouter"
    ]
  },
  {
    "id": "qwen-token-plan",
    "label": "Qwen Token Plan",
    "envVar": "QWEN_TOKEN_PLAN_API_KEY",
    "baseUrl": "https://token-plan.ap-southeast-1.maas.aliyuncs.com/compatible-mode/v1",
    "modelCount": 29,
    "providerIds": [
      "qwen-token-plan",
      "qwen-token-plan-individual"
    ]
  },
  {
    "id": "qwen-token-plan-cn",
    "label": "Qwen Token Plan CN",
    "envVar": "QWEN_TOKEN_PLAN_CN_API_KEY",
    "baseUrl": "https://token-plan.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
    "modelCount": 20,
    "providerIds": [
      "qwen-token-plan-cn"
    ]
  },
  {
    "id": "radius",
    "label": "Radius",
    "envVar": "RADIUS_API_KEY",
    "baseUrl": "https://radius.pi.dev/v1",
    "modelCount": 27,
    "providerIds": [
      "radius"
    ]
  },
  {
    "id": "together",
    "label": "Together",
    "envVar": "TOGETHER_API_KEY",
    "baseUrl": "https://api.together.ai/v1",
    "modelCount": 22,
    "providerIds": [
      "together"
    ]
  },
  {
    "id": "vercel-ai-gateway",
    "label": "Vercel AI Gateway",
    "envVar": "AI_GATEWAY_API_KEY",
    "baseUrl": "https://ai-gateway.vercel.sh",
    "modelCount": 236,
    "providerIds": [
      "vercel-ai-gateway"
    ]
  },
  {
    "id": "xai",
    "label": "xAI",
    "envVar": "XAI_API_KEY",
    "baseUrl": "https://api.x.ai/v1",
    "modelCount": 3,
    "providerIds": [
      "xai"
    ]
  },
  {
    "id": "xiaomi",
    "label": "Xiaomi",
    "envVar": "XIAOMI_API_KEY",
    "baseUrl": "https://api.xiaomimimo.com/v1",
    "modelCount": 3,
    "providerIds": [
      "xiaomi"
    ]
  },
  {
    "id": "xiaomi-token-plan-ams",
    "label": "Xiaomi Token Plan AMS",
    "envVar": "XIAOMI_TOKEN_PLAN_AMS_API_KEY",
    "baseUrl": "https://token-plan-ams.xiaomimimo.com/v1",
    "modelCount": 2,
    "providerIds": [
      "xiaomi-token-plan-ams"
    ]
  },
  {
    "id": "xiaomi-token-plan-cn",
    "label": "Xiaomi Token Plan CN",
    "envVar": "XIAOMI_TOKEN_PLAN_CN_API_KEY",
    "baseUrl": "https://token-plan-cn.xiaomimimo.com/v1",
    "modelCount": 2,
    "providerIds": [
      "xiaomi-token-plan-cn"
    ]
  },
  {
    "id": "xiaomi-token-plan-sgp",
    "label": "Xiaomi Token Plan SGP",
    "envVar": "XIAOMI_TOKEN_PLAN_SGP_API_KEY",
    "baseUrl": "https://token-plan-sgp.xiaomimimo.com/v1",
    "modelCount": 2,
    "providerIds": [
      "xiaomi-token-plan-sgp"
    ]
  },
  {
    "id": "zai",
    "label": "Z.AI",
    "envVar": "ZAI_API_KEY",
    "baseUrl": "https://api.z.ai/api/coding/paas/v4",
    "modelCount": 7,
    "providerIds": [
      "zai"
    ]
  },
  {
    "id": "zai-coding-cn",
    "label": "Z.AI Coding CN",
    "envVar": "ZAI_CODING_CN_API_KEY",
    "baseUrl": "https://open.bigmodel.cn/api/coding/paas/v4",
    "modelCount": 4,
    "providerIds": [
      "zai-coding-cn"
    ]
  }
];

/**
 * OAuth flows upstream ships. HappyVibe surfaces these; anything upstream adds
 * beyond them fails the contract test rather than appearing unreviewed.
 */
export const OAUTH_CATALOG: readonly CatalogOAuthProvider[] = [
  {
    "id": "anthropic",
    "label": "Anthropic",
    "isSubscription": true
  },
  {
    "id": "github-copilot",
    "label": "GitHub Copilot",
    "isSubscription": true
  },
  {
    "id": "kimi-coding",
    "label": "Kimi For Coding",
    "loginLabel": "Sign in with Kimi Code",
    "isSubscription": true
  },
  {
    "id": "meta",
    "label": "Meta",
    "loginLabel": "Sign in with Meta",
    "isSubscription": true
  },
  {
    "id": "openai-codex",
    "label": "OpenAI Codex",
    "isSubscription": true
  },
  {
    "id": "openrouter",
    "label": "OpenRouter",
    "loginLabel": "Sign in with OpenRouter"
  },
  {
    "id": "radius",
    "label": "Radius"
  },
  {
    "id": "xai",
    "label": "xAI",
    "loginLabel": "Sign in with SuperGrok or X Premium",
    "isSubscription": true
  }
];

/** Upstream OAuth flows deliberately NOT surfaced, with the reason. */
export const OAUTH_NOT_ENABLED: Readonly<Record<string, string>> = {};

/** The cards that stay above the "More providers…" search. */
export const FEATURED_PROVIDER_IDS = ["deepseek", "anthropic", "openai", "google", "openrouter"] as const;
