// GENERATED by `npm run catalog:tool-weights` (tools/tool-weights/build.ts). Do not edit.
// Tokens = characters ÷ 4, the context gauge's unit. Import-free: the renderer reads it.
export const TOOL_WEIGHTS = {
  "pi": "1.0.2",
  "compactionReserve": 16384,
  "total": 13243,
  "families": {
    "plan": 402,
    "terminal": 600,
    "browser": 1123,
    "web": 998,
    "document": 244,
    "memory": 953,
    "schedules": 1293,
    "subagents": 4488,
    "skills": 1192,
    "intent": 1008,
    "mcp": 0,
    "askUser": 365,
    "workflows": 6469,
    "images": 153
  },
  "core": {
    "read": 183,
    "bash": 218,
    "edit": 440,
    "write": 122,
    "grep": 0,
    "find": 0,
    "ls": 0
  },
  "tools": {
    "read": 653,
    "bash": 512,
    "edit": 1148,
    "write": 399,
    "Agent": 12719,
    "get_subagent_result": 690,
    "steer_subagent": 689,
    "ask_user": 1458,
    "use_skill": 417,
    "terminal_run": 981,
    "terminal_read": 788,
    "terminal_kill": 456,
    "browser_open": 709,
    "browser_navigate": 417,
    "browser_screenshot": 423,
    "browser_get_text": 369,
    "browser_read_console": 446,
    "browser_read_network": 458,
    "browser_click": 383,
    "browser_type": 478,
    "browser_evaluate": 527,
    "browser_close": 280,
    "web_search": 914,
    "web_fetch": 1093,
    "web_map": 638,
    "web_crawl": 1184,
    "document_read": 977,
    "memory_save": 1138,
    "memory_recall": 588,
    "memory_forget": 623,
    "schedule_list": 188,
    "schedule_create": 2323,
    "schedule_update": 2225,
    "schedule_delete": 435,
    "plan_complete": 510,
    "plan_start": 397,
    "plan_status_update": 702
  }
} as const;

export type WeightedFamily = keyof typeof TOOL_WEIGHTS.families;
export type CoreTool = keyof typeof TOOL_WEIGHTS.core;
