/**
 * Generates src/main/toolWeights.generated.ts — what each tool family adds to
 * EVERY request, measured on a key-free Pi with the app's real spawn args.
 * Run: npm run catalog:tool-weights. Re-run on a Pi bump or any change to a
 * tool's schema, description or prompt line (tests/tool-weights.test.ts says when).
 *
 * Each family = (reference) − (reference with that family off), so the prompt
 * text a family adds is counted with its schemas. Workflows and Images are off
 * in the reference (Workflows ships off; Images needs OpenRouter), so they are
 * measured the other way round. Ask user can't go off while Plan is on, so it
 * is measured with Plan off.
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { measure, piVersion, RUNTIME, type Variant } from "./measure.ts";
import { CORE_TOOLS } from "../../pi-runtime/extensions/hv-builtins.ts";

const tok = (chars: number): number => Math.round(chars / 4);
const total = async (v: Variant = {}): Promise<number> => (await measure(v)).totalChars;

const ref = await measure();
const minus = async (v: Variant): Promise<number> => tok(ref.totalChars - (await total(v)));
const plus = async (v: Variant): Promise<number> => tok((await total(v)) - ref.totalChars);

const families: Record<string, number> = {};
for (const k of ["plan", "terminal", "browser", "web", "document", "memory", "schedules", "subagents", "skills", "intent", "mcp"] as const) {
  families[k] = await minus({ builtins: { [k]: false } });
  console.log(k, families[k]);
}
const planOff = await total({ builtins: { plan: false } });
families.askUser = tok(planOff - (await total({ builtins: { plan: false, askUser: false } })));
families.workflows = await plus({ builtins: { workflows: true } });
families.images = await plus({ images: true });

const core: Record<string, number> = {};
for (const t of CORE_TOOLS) core[t] = await minus({ builtins: { coreOff: [t] } });

const pi = await import(pathToFileURL(path.join(RUNTIME, "node_modules/@earendil-works/pi-coding-agent/dist/index.js")).href);
const reserve = (pi.DEFAULT_COMPACTION_SETTINGS as { reserveTokens: number }).reserveTokens;

if (families.mcp !== 0) {
  // §13/§22: MCP is not a kit tile because it weighs nothing until a server exists.
  throw new Error(`MCP with no server weighs ${families.mcp} tokens — the kit's "MCP is not a tile" decision needs revisiting. Stop and report.`);
}

const out = `// GENERATED by \`npm run catalog:tool-weights\` (tools/tool-weights/build.ts). Do not edit.
// Tokens = characters ÷ 4, the context gauge's unit. Import-free: the renderer reads it.
export const TOOL_WEIGHTS = ${JSON.stringify({
  pi: piVersion(),
  compactionReserve: reserve,
  total: tok(ref.totalChars),
  families,
  core,
  tools: ref.toolChars,
}, null, 2)} as const;

export type WeightedFamily = keyof typeof TOOL_WEIGHTS.families;
export type CoreTool = keyof typeof TOOL_WEIGHTS.core;
`;
fs.writeFileSync(path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../../src/main/toolWeights.generated.ts"), out);
console.log("wrote src/main/toolWeights.generated.ts");
